baseURL = ""
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Open source education platform for Indian Competitive exams"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Open source education platform for Indian Competitive exams"
  author = "Sourabh Aggarwal"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Open source education platform for Indian Competitive exams"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/sourabh2311/MuftEducation.in"
weight = 10